notifications:
  email: false

language: cpp
sudo: false

compiler:
  - gcc
  - clang
os:
  - linux
  - osx

matrix:
  exclude:
    - os: osx
      compiler: gcc

script:
  - cd $TRAVIS_BUILD_DIR/simulator
  - make mipt-mips
  - make test
  - if [ $CXX == clang++-4.0 ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then make TIDY=clang-tidy-4.0 tidy; fi

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-4.0
    packages:
    - g++-6
    - clang-4.0
    - clang-tidy-4.0
    - llvm-4.0-dev
    - libelf-dev
    - libboost1.55-all-dev
    - texinfo

install:
  - git submodule init
  - git submodule update
  - if [ $CXX == g++ ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then CXX=g++-6; fi
  - if [ $CXX == clang++ ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then CXX=clang++-4.0; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install libelf; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export CPATH=$CPATH:/usr/local/Cellar/libelf/0.8.13_1/include/libelf; fi
  - OLD_CC=$CC
  - OLD_CXX=$CXX
  - CC=gcc
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then CC=gcc-4.8; fi
  - CXX=g++
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then CXX=g++-4.8; fi
  - cd $TRAVIS_BUILD_DIR/binutils
  - ./configure --target=mipsel-unknown-linux-gnu
  - make
  - CC=$OLD_CC
  - CXX=$OLD_CXX
